/**
 * WS protocol shapes — the single contract between this server and the
 * Flutter/web client. Server messages in ServerMessage, client commands in
 * ClientCommand. Keep in sync with the app fork.
 */

export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
  reasoning: boolean;
  contextWindow?: number;
  vision: boolean;
}

export interface ToolImage {
  data: string;
  mimeType: string;
}

export interface ToolEvent {
  callId: string;
  name: string;
  args?: unknown;
  result?: string;
  images?: ToolImage[];
  isError?: boolean;
  running: boolean;
  /** Timestamp in epoch milliseconds. */
  timestamp?: number;
}

/** A reference to an image the client can fetch on demand. Base64 never
 * travels in history: it is re-sent on every push and reload, and a real
 * transcript's eight 4K screenshots were 19.36 MB of a 19.7 MB payload. */
export interface HistoryImage {
  id: string;
  mimeType: string;
  bytes: number;
}

export interface HistoryItem {
  id?: string;
  role: "user" | "assistant" | "system";
  customType?: string;
  text: string;
  /** Thinking/reasoning text generated by the model, if any. */
  thinking?: string;
  /** Timestamp in epoch milliseconds when the message was recorded. */
  timestamp?: number;
  /** Images the MESSAGE itself carried (user image attachments), by reference. */
  images?: HistoryImage[];
  tools: Array<{
    name: string;
    args?: unknown;
    id?: string;
    result?: string;
    isError?: boolean;
    /** Timestamp in epoch milliseconds when the tool call was made or returned. */
    timestamp?: number;
    /** Images the tool result carried (e.g. an image `read`), by reference. A
     * LIVE tool call still carries `data` inline — that is a single one-off
     * payload, while history repeats on every push. */
    images?: Array<HistoryImage & { data?: string }>;
  }>;
}

/** Registry row (durable, on disk). */
export interface SessionRow {
  id: string;
  name?: string;
  cwd?: string;
  /** pi's own session JSONL file — the resume anchor. */
  piSessionPath?: string | null;
  model?: string | null;
  modelName?: string | null;
  thinkingLevel?: string;
  status?: "running" | "idle" | "closed";
  isInteractive?: boolean;
  isHost?: boolean;
  createdAt?: number;
  updatedAt?: number;
  // overlay fields added by session_list (mergedRegistryRows)
  live?: boolean;
  resumed?: boolean;
}

/** Live in-memory snapshot for a session managed by this process.
 * Status vocabulary here is activity ("idle"/"working"), not durability. */
export interface SessionSnapshot {
  id: string;
  status: "idle" | "working";
  name?: string;
  cwd?: string;
  streamingText?: string | null;
  streamingThinking?: string | null;
  contextUsage?: unknown;
  model?: string | null;
  modelName?: string | null;
  thinkingLevel?: string;
  isInteractive?: boolean;
  isHost?: boolean;
  createdAt?: number;
  resumed?: boolean;
  /** Messages submitted but not yet delivered into the session (server-authoritative queue). */
  pendingMessages?: string[];
  /** The subset of `pendingMessages` submitted as STEERS. A steer waits for
   * the assistant's current step to end, not for the whole turn, so the client
   * must be able to tell the two apart — and it must survive a client reload,
   * which client-side bookkeeping does not. */
  pendingSteering?: string[];
  /** Attached images for pending queued/steering messages, preserved across client reloads. */
  pendingImagesByText?: Record<string, UserImage[]>;
  /** True while a compact() is in flight for this session. */
  isCompacting?: boolean;
  /** A provider error the agent is retrying on its own. Without this the app
   * showed only a repeating error toast and the user had nothing to stop: the
   * retry loop belongs to pi and only an abort on THAT session ends it. */
  retry?: { attempt: number; maxAttempts: number; delayMs: number; errorMessage: string } | null;
  /** Background jobs running or recently finished for this session. */
  jobs?: BackgroundJobSummary[];
}

export interface BackgroundJobSummary {
  id: string;
  command: string;
  name?: string;
  cwd: string;
  sessionId?: string;
  pid?: number;
  startedAt: number;
  finishedAt?: number;
  status: "running" | "completed" | "failed" | "cancelled";
  exitCode?: number | null;
  error?: string;
  logPath: string;
  totalBytes: number;
}

export type ServerMessage =
  | { type: "authed" }
  | { type: "pong" }
  | { type: "error"; message: string; sessionId?: string }
  /** Something the user asked for HAPPENED (compact/clear). Silence is what
   * made these look like no-ops; the client shows this as a snackbar. */
  | { type: "notice"; sessionId?: string; message: string }
  | { type: "state"; online: boolean; hostname: string; homePath?: string; activeSessionId?: string | null; sessions: SessionSnapshot[]; registry: SessionRow[]; tunnelUrl?: string | null; tunnelProvider?: string | null }
  | { type: "session_list"; sessions: SessionRow[] }
  | { type: "session_deleted"; sessionId: string; deleted: boolean }
  | { type: "jobs_list"; sessionId?: string; jobs: BackgroundJobSummary[] }
  | { type: "job_update"; sessionId?: string; job: BackgroundJobSummary }
  | { type: "job_logs"; jobId: string; logs: string; truncated: boolean; path: string; cmdId?: string }
  | { type: "history"; sessionId: string; history: HistoryItem[];
      /** Page the client asked for / the server decided to push. */
      cursor: number; hasMore: boolean; mode: "replace" | "older";
      /** The transcript was rewritten (compact/clear), so the client must
       * discard every previously loaded page before applying this one. */
      reset?: boolean }
  | { type: "stream"; sessionId: string; text: string; status: string; segments?: Array<{ text: string; atTool: number }>; thinking?: string }
  | { type: "tool"; sessionId: string; tool: ToolEvent }
  | { type: "models"; sessionId?: string; models: ModelInfo[] }
  | { type: "paths"; cmdId?: string; paths: string[] }
  | { type: "session_tree"; sessionId: string; tree: unknown[]; leafId: string | null; cmdId?: string; editorText?: string }
  | { type: "session_rewound"; sessionId: string; entryId: string; editorText?: string; cmdId?: string }
  | { type: "queue_parked"; sessionId: string; messages: Array<{ text: string; images: UserImage[] }> }
  | { type: "image"; imageId: string; mimeType: string; data: string }
  | { type: "image_missing"; imageId: string; reason: string }
  | { type: "path_check"; cmdId?: string; exists: boolean; isDirectory: boolean }
  | { type: "folder_created"; cmdId?: string; path?: string; error?: string };

/** An image attached by the client to a user_message (paste/upload). */
export interface UserImage {
  mimeType: string;
  /** base64-encoded image bytes */
  data: string;
}

export type ClientCommand =
  | { type: "ping" }
  | { type: "user_message"; sessionId?: string; text: string; id?: string; images?: UserImage[]; deliverAs?: "steer" | "followUp" }
  | { type: "cancel"; sessionId?: string }
  | { type: "model_set"; sessionId?: string; provider: string; modelId: string }
  | { type: "thinking_set"; sessionId?: string; level: string }
  | { type: "session_compact"; sessionId?: string }
  | { type: "session_new"; sessionId?: string }
  | { type: "session_spawn"; sessionId?: string; cwd?: string; name?: string; model?: string }
  | { type: "session_despawn"; sessionId: string }
  | { type: "session_list" }
  | { type: "session_resume"; sessionId: string }
  | { type: "session_rename"; sessionId: string; name: string }
  | { type: "session_select"; sessionId: string }
  | { type: "session_delete"; sessionId: string; deleteHistory?: boolean }
  | { type: "list_models"; sessionId?: string }
  | { type: "get_history"; sessionId?: string; limit?: number;
      /** Index of the oldest item the client already holds — request the
       * page BEFORE it (scroll-back pagination). */
      cursor?: number }
  | { type: "queue_clear"; sessionId?: string }
  | { type: "queue_delete"; sessionId?: string; text: string }
  | { type: "session_tree_get"; sessionId?: string; id?: string }
  | { type: "session_tree_navigate"; sessionId?: string; entryId: string; summarize?: boolean; id?: string }
  | { type: "session_rewind"; sessionId?: string; entryId: string; id?: string }
  | { type: "list_paths"; sessionId?: string; prefix?: string; id?: string }
  | { type: "path_check"; path: string; id?: string }
  | { type: "folder_create"; path: string; id?: string }
  | { type: "set_compact_threshold"; thresholdTokens: number }
  | { type: "set_max_image_bytes"; maxBytes: number; id?: string }
  | { type: "jobs_list"; sessionId?: string }
  | { type: "job_kill"; jobId: string; sessionId?: string }
  | { type: "job_logs"; jobId: string; maxBytes?: number; tail?: boolean; id?: string; sessionId?: string }
  | { type: "get_image"; imageId: string; id?: string }
  | { type: "reload" };
