#!/usr/bin/env python3
"""Enforce repository source-file size limits.

The default limit prevents new monoliths. Existing oversized files have explicit
ceilings so they cannot grow while their owners extract cohesive modules.
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


DEFAULT_LINE_LIMIT = 1_200
LEGACY_LINE_LIMITS = {
    Path("app/lib/screens/chat_screen.dart"): 1_595,
    Path("server/src/index.ts"): 1_290,
}

SOURCE_SUFFIXES = frozenset(
    {
        ".c",
        ".cc",
        ".cpp",
        ".cxx",
        ".dart",
        ".h",
        ".hh",
        ".hpp",
        ".hxx",
        ".java",
        ".js",
        ".jsx",
        ".kt",
        ".kts",
        ".mjs",
        ".cjs",
        ".py",
        ".swift",
        ".ts",
        ".tsx",
    }
)

EXCLUDED_DIRECTORY_NAMES = frozenset(
    {
        ".dart_tool",
        ".git",
        ".gradle",
        ".idea",
        ".pub-cache",
        ".venv",
        ".vscode",
        "Pods",
        "__pycache__",
        "build",
        "coverage",
        "dist",
        "ephemeral",
        "generated",
        "node_modules",
        "out",
        "scratch",
        "third_party",
        "vendor",
    }
)

GENERATED_FILENAME_PARTS = (
    ".freezed.",
    ".g.dart",
    "generated_plugin_registrant",
)

GENERATED_HEADER_MARKERS = (
    "@generated",
    "automatically generated",
    "generated code",
    "generated-style file",
    "generated by the protocol buffer compiler",
)


@dataclass(frozen=True)
class Violation:
    path: Path
    line_count: int
    line_limit: int


def count_lines(path: Path) -> int:
    """Count logical text lines, including a final line without a newline."""

    with path.open("rb") as source:
        contents = source.read()
    if not contents:
        return 0
    return contents.count(b"\n") + (not contents.endswith(b"\n"))


def is_generated_source(path: Path) -> bool:
    lowercase_name = path.name.lower()
    if any(part in lowercase_name for part in GENERATED_FILENAME_PARTS):
        return True

    try:
        with path.open("r", encoding="utf-8", errors="replace") as source:
            header = "".join(next(source, "") for _ in range(8)).lower()
    except OSError:
        return False
    return any(marker in header for marker in GENERATED_HEADER_MARKERS)


def iter_source_files(root: Path) -> Iterable[Path]:
    """Yield first-party source files without entering generated/vendor trees."""

    for directory, child_directories, filenames in os.walk(root, followlinks=False):
        child_directories[:] = sorted(
            name
            for name in child_directories
            if name not in EXCLUDED_DIRECTORY_NAMES
        )
        directory_path = Path(directory)
        for filename in sorted(filenames):
            path = directory_path / filename
            if path.suffix.lower() not in SOURCE_SUFFIXES:
                continue
            if path.is_symlink() or is_generated_source(path):
                continue
            yield path


def find_violations(root: Path) -> list[Violation]:
    root = root.resolve()
    violations: list[Violation] = []
    for path in iter_source_files(root):
        relative_path = path.relative_to(root)
        line_limit = LEGACY_LINE_LIMITS.get(relative_path, DEFAULT_LINE_LIMIT)
        line_count = count_lines(path)
        if line_count > line_limit:
            violations.append(Violation(relative_path, line_count, line_limit))
    return violations


def format_violation(violation: Violation) -> str:
    return (
        f"{violation.path.as_posix()}: {violation.line_count} lines "
        f"(limit {violation.line_limit})"
    )


def parse_args(arguments: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fail when a first-party source file exceeds its structure limit."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (defaults to this tool's repository)",
    )
    return parser.parse_args(arguments)


def main(arguments: Sequence[str] | None = None) -> int:
    options = parse_args(arguments)
    root = options.root.resolve()
    if not root.is_dir():
        print(f"structure check refused: repository root is not a directory: {root}")
        return 2

    violations = find_violations(root)
    if violations:
        print("Source structure check failed:")
        for violation in violations:
            print(f"  {format_violation(violation)}")
        return 1

    print(f"Source structure check passed (default limit {DEFAULT_LINE_LIMIT} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
